### ISSUE TITLE
Install msgfmt, part of GNU get text tools.

### ISSUE THREAD

**Issue by benhutchins** [benhutchins/docker-taiga#1]
When running `python manage.py compile messages` as part of the initial database setup, it fails because it's missing a required dependency. Error thrown:

```
CommandError: Can't find msgfmt. Make sure you have GNU gettext tools 0.15 or newer installed.
```

**Comment by ryanemax** [comment]
how to install the gettext?

**Comment by jauyzed** [comment]
I saw this error but was able to hit the home page. But What are the creds to login?

**Comment by Folcky** [comment]
Once your container is running, use the default administrator account to login: username is admin, and the password is 123123.
