### ISSUE TITLE
How to run taiga not on 80 port?

### ISSUE THREAD

**Issue by ghost** [benhutchins/docker-taiga#10]
If simply change port for `benhutchins/taiga` container - taiga show an error.

**Comment by mrmoneyc** [comment]
@a93ushakov append port number to TAIGA_HOSTNAME in docker-compose.yml and modify docker port maping

**Comment by a93ushakov** [comment]
`docker-compose up`

```sh
ERROR: Service 'taiga' failed to build: The command '/bin/sh -c ln -s /taiga/conf.json /usr/src/taiga-front-dist/dist/conf.json' returned a non-zero code: 1
```

**Comment by mrmoneyc** [comment]
`taiga:
  build: .
  restart: always
  ports:
    - 7080:80
    # - 443:443 # To enable SSL, uncomment this line
  #links:
   # - postgres
   # - redis:redisio
   # - postgresql:postgresql
  volumes:
    - /share/Taiga/media:/usr/src/taiga-back/media
  environment:
    - TAIGA_HOSTNAME=172.17.31.13:7080`

That's a part of my `docker-compose.yml`, works for me.

**Comment by benhutchins** [comment]
Best way to do this is to just correct the port you map, in docker run it'd be `-p 8080:80` (`8080` being the port you want). Or use `docker-compose`, see @mrmoneyc's example where he specified port `7080`. Please be sure to update the `TAIGA_HOSTNAME` to include the port if it's non-standard.
