### ISSUE TITLE
ERROR: build path

### ISSUE THREAD

**Issue by gregoirelemoulant** [benhutchins/docker-taiga#13]
Hello, after cloning the project, I run `docker-compose up`
and I have this : 
`ERROR: build path /home/kad/mytaiga/simple/benhutchins/taiga either does not exist, is not accessible, or is not a valid URL.`

Thanks

**Comment by Bratik** [comment]
Hello,
same problem for me

**Comment by Bratik** [comment]
replacing build by image in my docker-compose.yml fixed the issue:
`
taiga:
image: benhutchins/taiga
`

**Comment by benhutchins** [comment]
Might have to explicitly run `docker-compose build`. Also might be the docker setup, older setups (back in ~Apr 2016) might still have been using docker-machine or similar, which had a lot of permission issues. I'll close this for now, but feel free to reopen if you need help.
