### ISSUE TITLE
Random problem with email & status updates

### ISSUE THREAD

**Issue by avalon12** [benhutchins/docker-taiga#18]
Hey, I have the strangest of issues with this taiga docker.

Emailing seems to work, as invitations are being sent, as well as the confirmation that follows up.

However, when I submit a comment on a US, with a mention in it for a user, an email is never sent. No other notifications seem to be emailed either.
Also, in the news feed not all these updates some to come up, and some randomness about when they do seems to occur. (i cant find any pattern)

My SMTP server isnt logging any activity, the docker logs dont show any error, what can I do to debug?

**Comment by benhutchins** [comment]
@avalon12 I'd have to setup something to recreate the issue you're seeing, although my guess is that if it's sending out emails properly, this might be a problem with Taiga, and not the docker setup. In which case, I'll check to see if there's been new Taiga releases. I won't be able to test this for 2-3 weeks however. If you want to test updating Taiga, just clone this repo, update the submodule to latest via `git submodule update --init --remote` and then build a new image from the `Dockerfile`.

**Comment by avalon12** [comment]
Started up the version of taiga docker from htdvisser/taiga-back, and it
doesnt show the issue. Im going to stick to that setup. Thanks!


Met vriendelijke groet,

R. Brondgeest

On Mon, Mar 13, 2017 at 2:13 PM, Benjamin Hutchins <notifications@github.com
