### ISSUE TITLE
Error in docker run TAIGA_DB_PASSWORD

### ISSUE THREAD

**Issue by JorisLA** [benhutchins/docker-taiga#19]
Hi !
Thank you for your work !

I followed the summarize , I run :

**docker run --name taiga-postgres -e POSTGRES_PASSWORD=password -d postgres
docker run --name taiga-redis -d redis:3
docker run --name taiga-rabbit -d --hostname taiga rabbitmq:3
docker run --name taiga-celery -d --link taiga-rabbit:rabbit celery
docker run --name taiga-events -d --link taiga-rabbit:rabbit benhutchins/taiga-events**

Then : 

**docker run -itd \
  --name taiga \
  --link taiga-postgres:postgres \
  --link taiga-redis:redis \
  --link taiga-rabbit:rabbit \
  --link taiga-events:events \
  -p 80:80 \
  -v /my/own/media:/usr/src/taiga-back/media \
  benhutchins/taiga**

The last container is exited and after a "docker logs": 

**Running database check
Traceback (most recent call last):
  File "/checkdb.py", line 12, in <module>
    "' password='" + DB_PASS + "'")
TypeError: Can't convert 'NoneType' object to str implicitly
Failed to connect to database server or database does not exist.**

I tried to pass variable with -e TAIGA_DB_PASSWORD=password in the last container but still.

regards,

**Comment by lukepolo** [comment]
what did you do to solve this?

**Comment by JorisLA** [comment]
--link is deprecated so I pass every environment variables in the docker taiga.
-e TAIGA_HOSTNAME=localhost
-e TAIGA_DB_NAME=taigadb
-e TAIGA_DB_HOST=postgres
-e TAIGA_DB_USER=postgres
-e TAIGA_DB_PASSWORD=password

And also in the docker taiga-postgres
-e POSTGRES_DB=taigadb
-e POSTGRES_USER=postgres
-e POSTGRES_PASSWORD=password

**Comment by lukepolo** [comment]
Thank you~

**Comment by lukepolo** [comment]
This also happens for the docker-compose , not sure how to fix that will try just doing it manually instead

**Comment by benhutchins** [comment]
@lukepolo You can add the environment variables with the `environment:` tag in the `docker-compose.yml` file. If you update your `docker-compose.yml` to `version: 2` or newer, it also no longer will share the environment variables as it used to. The file here https://github.com/benhutchins/docker-taiga/blob/master/docker-compose.yml shows example configuration where it specifies all of these required environment variables.

**Comment by lukepolo** [comment]
Ok will give it a go then~

**Comment by lukepolo** [comment]
Just as an update : 

Im not using version 2, uncommented variables in `environment` section (leaving the defaults alone) 


![image](https://cloud.githubusercontent.com/assets/2066668/24411199/4d230b94-13a3-11e7-835e-f42c91038d26.png)



`docker-compose build`
`docker-compose up`

![image](https://cloud.githubusercontent.com/assets/2066668/24411117/0ad72bbc-13a3-11e7-8264-19d174352b8d.png)


Im also using the example 
https://github.com/benhutchins/docker-taiga-example in the `advanced` part as the `simple` does not allow me even to run `docker-compose build` cause my version of docker does not allow for version 2 syntax~
