### ISSUE TITLE
Fix SSL configuration

### ISSUE THREAD

**Issue by benhutchins** [benhutchins/docker-taiga#2]
Currently, when using SSL, this warning is thrown:

```
[warn] 19#19: "ssl_stapling" ignored, issuer certificate not found
```

**Comment by andreabedini** [comment]
@benhutchins if I can offer my 2c I think the TLS termination with ngnix should be taken out of the web app container. It can be added back with a dedicated sidekick container, like we do with postgresql, redis, etc

**Comment by benhutchins** [comment]
I completely agree that if at all possible, SSL should be removed from this. Would just need to have a way to either tell the container it's running with SSL so it can dynamically update the `taiga/conf.json` file and to update the `taiga/local.py` variables (currently done by [`docker-settings.py`](https://github.com/benhutchins/docker-taiga/blob/6e597d6f078f759a7c222b59e5de2263294fccbf/docker-settings.py#L23)).

Probably makes sense to just keep the environment variable `TAIGA_SSL`, when provided, update those settings and assume there is something providing SSL other than this container.

**Comment by andreabedini** [comment]
@benhutchins thanks! I had a quick go last night and I realised we still need someone to serve the static content (the frontend). Either we share it as a volume with an external nginx or perhaps the backend can serve it too? I will make some tests.

By the way, you did a great job, docker set ups this tidy and clean are hard to come by, 100% will docker-compose up again!

**Comment by benhutchins** [comment]
That would be removing nginx entirely from the container, that's another step than just removing SSL. I've played with that before and had the same roadblocks. It would significantly increase the complication to get up and running, although if you provided a reasonable `docker-compose.yml` file still it helps people get started.

**Comment by benhutchins** [comment]
Recently added support for having externally provided SSL, so I believe this issue is resolved.
