### ISSUE TITLE
Docker Compose UP - DB Issue

### ISSUE THREAD

**Issue by lukepolo** [benhutchins/docker-taiga#21]
I cloned , went to advanced , then `docker-compose build` then `docker-compose up` and i get the following 

![image](https://cloud.githubusercontent.com/assets/2066668/24371786/f0c62722-12f9-11e7-8195-5a2fbaa5d957.png)

taiga_1    | Running database check
taiga_1    | Traceback (most recent call last):
taiga_1    |   File "/checkdb.py", line 12, in <module>
taiga_1    |     "' password='" + DB_PASS + "'")
taiga_1    | TypeError: Can't convert 'NoneType' object to str implicitly
taiga_1    | Failed to connect to database server or database does not exist.
advanced_taiga_1 exited with code 1

**Comment by JanoschDeurer** [comment]
Same issue here, I found out, that if you set the the HOST, USER and NAME variables as follows:
`    TAIGA_DB_HOST: postgres
    TAIGA_DB_NAME: postgres
    TAIGA_DB_USER: postgres`
this solves the error. seems like there is something wrong with the default values

**Comment by benhutchins** [comment]
This appears resolved by specifying the proper environmental variables.
