### ISSUE TITLE
ARM Architecture

### ISSUE THREAD

**Issue by benhutchins** [benhutchins/docker-taiga#23]
Unconfirmed. Got an email about a potential ARM architecture. Need to confirm, then fix if it is an issue.

**Comment by sjoerd222888** [comment]
Running on the ARM architecture requires you to start with another base image. I started with a Raspberry PI (armv6) and I tried first with [hypriot/rpi-python](https://hub.docker.com/r/hypriot/rpi-python/) but failed installing nginx as armv6 is not supported. After messing around a bit I decided to start with a new Dockerfile based on Arch Linux where I have nginx available for also for armv6 (however I later switcher to a Raspberry V2 with armv7).

Of course you also have to pick an arm image for postgres, e.g. [ldouchy/rpi-postgres](https://hub.docker.com/r/ldouchy/rpi-postgres/).

I hope this information is some help.

**Comment by mcrosson** [comment]
I can confirm the docker build works as-is on arm7l and arm8.

As long as the host has the ```arch``` label set to ```arm32``` or ```arm64``` it'll work.

Note: this will only work with the raspberry pi's that have arm7l or arm8 chips (currently the 3b and 3b+)
