### ISSUE TITLE
Error checkdb.py

### ISSUE THREAD

**Issue by Salimlou** [benhutchins/docker-taiga#3]
Hi,

first of all thanks for this repo! life saving :)!

But there is a small error in checkdb.py 
in this line : 
conn = psycopg2.connect("dbname='" + DB_NAME + "' user='" + DB_USER + "' host='" + DB_USER + "' password='" + DB_PASS + "'")

the host is filled with DB_USER instead of DB_HOST.

Thks @benhutchins!

**Comment by benhutchins** [comment]
Thanks for the report! Resolved it with 142dc17. Glad to hear someone other than myself is actually using this.
