### ISSUE TITLE
Specify DB Port

### ISSUE THREAD

**Issue by davaxi** [benhutchins/docker-taiga#37]
Hi,

How i can specify other port for database connection ? `TAIGA_DB_PORT` ?

Thanks

**Comment by benhutchins** [comment]
You can't!

That's a gap in the support for databases. Seemed to have just been missed.

I will add support for the `TAIGA_DB_PORT`

**Comment by vdelacerda** [comment]
Hi,
Have you still planned to add the `TAIGA_DB_PORT `variable ?
It would be great !
