### ISSUE TITLE
Error on docker-compose up -d

### ISSUE THREAD

**Issue by chamunks** [benhutchins/docker-taiga#4]
Error on `docker-compose up -d`

    Building taiga
    Step 1 : FROM benhutchins/taiga
     ---> 6ed4caccab5a
    Step 2 : MAINTAINER Benjamin Hutchins <ben@hutchins.co>
     ---> Using cache
     ---> d82557f3010d
    Step 3 : RUN pip install --no-cache-dir       taiga-contrib-slack       taiga-contrib-ldap-auth
     ---> Using cache
     ---> f87d806e491f
    Step 4 : COPY slack.js /usr/src/taiga-front-dist/dist/js/slack.js
    ERROR: Service 'taiga' failed to build: stat slack.js: no such file or directory

I attempted to comment out the slack plugin as I won't be needing slack integration to remedy the issue to no avail.

**Comment by chamunks** [comment]
The readme makes no mention about the file being added in the Dockerfile so I just commented that out after examining it.

**Comment by benhutchins** [comment]
@chamunks This project doesn't use the Slack plugin at all, if you were using the example `docker-compose.yml` from https://github.com/benhutchins/docker-taiga-example then that project's `README.md` does go over configuring [Slack](https://github.com/benhutchins/docker-taiga-example#slack).
