### ISSUE TITLE
Update to 3.3.1 (and over 2018)

### ISSUE THREAD

**Issue by IwishIcanFLighT** [benhutchins/docker-taiga#48]
Hi !

I would like to update my taiga instance to 3.3.1 as it adds quite a load of cool features such as live notifications:

https://github.com/taigaio/taiga-back/blob/master/CHANGELOG.md

The issue is that I'm using this docker template and I have no idea how to update it. Any help would be greatly appreciated @benhutchins ! :wink: 

Beside, the Taiga dev team [planned quite some cool stuff for 2018](https://blog.taiga.io/taiga-plans-for-2018.html) and I'm wondering if this docker template will follow the pace of the releases over the year.

Thanks!

**Comment by linkerx** [comment]
Hi @IwishIcanFLighT im using this docker image too and want to update. Version 3.3 add some big features like due dates and time views that will help me a lot managing projects priorities. Im trying to understand how is this made to update without breaking @benhutchins structure.

**Comment by IwishIcanFLighT** [comment]
Thanks I'll give it a try next week !

**Comment by IwishIcanFLighT** [comment]
@linkerx Are you also using the slack contrib plugin and/or any other plugin with this method?
I'm trying to figure out how to install it.

I've been using the [docker-taiga-example](https://github.com/benhutchins/docker-taiga-example) repo so far and need to rollback to this repo if I want to upgrade but I don't want to lose the plugin. :confused:

**Comment by IwishIcanFLighT** [comment]
Alright I managed to upgrade and install the slack plugin easily. Simply had to add the slack plugin lines in the Dockerfile and local.py like it's done in the [docker-taiga-example](https://github.com/benhutchins/docker-taiga-example).

However I'm still struggling to install and update docker event. 3.3.0 brings live notification to taiga via events so I can't miss this upgrade...

I might have to dig in @benhutchins's [docker-taiga-event repo](https://github.com/benhutchins/docker-taiga-events) as well...

Any help is welcome!

**Comment by benhutchins** [comment]
Correct, it should ideally be easy to update to the latest version of taiga by updating the submodules. I've just merged in #15 to keep the core closer to latest though.

**Comment by IwishIcanFLighT** [comment]
@benhutchins This update is much appreciated. Thanks.
However are you planning on updating taiga-event as well? I can't figure out how to make it work with the new live notifications.
