### ISSUE TITLE
[Question] Would you be willing to write a list of volumes for persistent data?

### ISSUE THREAD

**Issue by chamunks** [benhutchins/docker-taiga#5]
I'm wondering where to set volumes directives to.

**Comment by benhutchins** [comment]
Volumes for what? Taiga is stored in `/usr/src/`, as `/usr/src/taiga-front-dist` and `/usr/src/taiga-back`. 

Configuration is pulled from `/taiga`.
- `/taiga/local.py` is the taiga-back configuration file.
- `/taiga/conf.json`is the taiga-front configuration file.
The [example](https://github.com/benhutchins/docker-taiga-example) project shows how to override these configuration files and optionally add additional plugins to Taiga.

I haven't yet addressed persistent storage, such as uploaded user icons and attachments. That would likely be an issue worth investigating.

**Comment by benhutchins** [comment]
Have done this now.

**Comment by chamunks** [comment]
Awesome thanks!  I like to know where all of the volatile data is in the containers that I run to meet my backup conventions.
