### ISSUE TITLE
Taiga error but nothing wrong in stdout

### ISSUE THREAD

**Issue by ajira86** [benhutchins/docker-taiga#50]
Hello,

I'm trying to run Taiga through Synology Docker interface. After some tests the system launch, connect to postgresql container and land me to the discover page. Unfortunatly I have an error message "Something happened and our Oompa Loompas are working on it." and don't know how to debug it.

Synology provide to me logs and terminal output but nothing seams wrong. What can I do from here ? Is there a way to enable a more verbose debug mode ? Or perhaps enable debug directly in Django ?

Thanks in advance for your help.

**Comment by ajira86** [comment]
Ok, never mind, I just changed the port after the first container start. So system tried to call backend from the wrong port.

**Comment by amjha** [comment]
I am facing the same issue. I tried mapping port through portainer.io but it did not help.
Can you provide details for changing the port for back end call?

**Comment by ajira86** [comment]
The problem it that hostname is replaced in configuration at container creation. I rewrite docker entrypoint file to fix it in my own "fork" if you are interested. But if you want a quick wait, you should simply delete and rebuilt your container. **Ensure to have your data in a linked volume and an external database before doing this**.

**Comment by benyanke** [comment]
I also have a fork which I'm using in production which you might try.

http://github.com/benyanke/docker-taiga
