### ISSUE TITLE
django.db.utils.ProgrammingError: type "jsonb" does not exist

### ISSUE THREAD

**Issue by Xiaolei1200** [benhutchins/docker-taiga#59]
When I directto run：
docker run -itd --name mytaiga -p 90:80 -e TAIGA_HOSTNAME=asura.xin -v /media:/usr/src/taiga-back/media -e TAIGA_DB_NAME=postgres -e TAIGA_DB_HOST="myhost" -e TAIGA_DB_USER=postgres -e TAIGA_DB_PASSWORD="mypasswd" benhutchins/taiga
It error：
![image](https://user-images.githubusercontent.com/37185679/41477806-0e04be86-70f8-11e8-87de-0d3a2ee61550.png)
I need help！

**Comment by ajira86** [comment]
Could you please tell us which postgresql version your are trying to link, it seams to be an error with postgresql 9.3 (and perhaps all versions before) ?

Note for the doc: taiga-back need postgresql >= 9.4 (https://taigaio.github.io/taiga-doc/dist/setup-production.html#_prerequisites) we should inform Docker users about that.

> The component taiga-back uses postgresql (>= 9.4) as database:
