### ISSUE TITLE
Update to the latest Taiga version

### ISSUE THREAD

**Issue by corentincharron** [benhutchins/docker-taiga#70]
Hello,

I'm using your image on my server. How could I upgrade to the latest Taiga version (which has new important features to me)?

Thanks a lot

**Comment by benhutchins** [comment]
Ideally, the process would only require you to run:

`git submodule update --init --remote`

However, based on some other issues I think updating Nginx and some other aspects of this project may be required. I'm going through issues and pull requests now, but you will likely need to pull the newer image.

**Comment by lonix1** [comment]
@corentincharron Were you able to upgrade to latest version with that command, or was there more to do? This version is quite ancient so I'd like to upgrade too.

**Comment by corentincharron** [comment]
No, I just re-installed everything as I needed to clean my install anyway. Sorry I can't help more :/

**Comment by lonix1** [comment]
@benhutchins Where is that command supposed to be run?

I shelled into the running container, I'm logged into `/usr/src/` which has the "back" and "front" directories, but neither is a git directory.

The `.git` also points to a non-existent git submodules directory. Is updating actually possible?
