### ISSUE TITLE
Custom port

### ISSUE THREAD

**Issue by lonix1** [benhutchins/docker-taiga#78]
I want to use port `8000`, not `80`.

There are various workarounds in other issues, but they don't work anymore. In fact, after applying some of those workarounds, I managed got it working on port `80` AND `8000` at the same time! Also not good! :laughing: 

Has anyone managed to get this working (properly) on a different port?

**Comment by lonix1** [comment]
Okay [this is part of the problem](https://github.com/benhutchins/docker-taiga/blob/master/Dockerfile#L77):

````
EXPOSE 80 443
````

It should not be hardcoded like that.

So even if we manage to use custom port, it still ALSO serves on 80.

**Comment by benhutchins** [comment]
Generally the port used by the Docker container doesn't have to change, you usually need to bind the port to a port on the host which can be specified easily.

```
docker run -p 8000:80 benhutchins/taiga
```

That will bind it to port 8000 on the Docker host.

Using `EXPOSE` is a best practice.

**Comment by lonix1** [comment]
That doesn't apply though when using docker-compose... So we do this instead:
````
ports
  - 8000:80
````

But 1) if following all the other workarounds mentioned in the other issues, and 2) doing the above, then both 8000 and 80 are exposed at the same time. :disappointed:

**Comment by benhutchins** [comment]
Both ports are being exposed on the host? Even though you specified, in your docker-compose file, `- 8000:80`?

Can you share a `docker info` and `docker ps` output? It sounds like an issue with the docker networks and not with the image

**Comment by lonix1** [comment]
`docker ps` shows: `443/tcp, 0.0.0.0:8000->80/tcp`. Looks legit. But 80 on the host is still exposed, weird.

Interestingly, `localhost:8000` works, and `localhost` sometimes works and sometimes complains about the oompa loompas. So maybe it's a problem in the underlying scripts.

I'm gonna close, but it anyone else has this problem, then we can investigate.
