### ISSUE TITLE
[Django] Upgrading to 1.9 ?

### ISSUE THREAD

**Issue by p418** [benhutchins/docker-taiga#8]
Hi Benjamin, 

First of all, thank you for your work.
I encountered some issues when trying to use Taiga api ('/api/v1/') and it seems that it can be partially fixed by upgrading django to 1.9 version.

When  I try to perform a `pip3.4 install -U Django` command, it crashes  my container. 

Have you ever tried to do this?

**Comment by benhutchins** [comment]
I have not, but I've got some time allocated to update this project this week, so I'll be updating it to the latest Taiga version and working through some upgrade issues.

**Comment by p418** [comment]
Great!

Also, if you can include volumes in your Dockerfile, it would be a good nice.
For example, I noticed that uploaded medias are stored into `/usr/src/taiga-back/media` folder.

**Comment by benhutchins** [comment]
This should be resolved now that Taiga has been updated. I've also added a note about the volumes and included it in the examples.
