### ISSUE TITLE
[ FAILURE ] docker-compose up trouble

### ISSUE THREAD

**Issue by ghost** [benhutchins/docker-taiga#9]
``` sh
Step 20 : RUN ln -s /taiga/conf.json /usr/src/taiga-front-dist/dist/conf.json
 ---> Running in 33360a74469e
ln: failed to create symbolic link ‘/usr/src/taiga-front-dist/dist/conf.json’: No such file or directory
ERROR: Service 'taiga' failed to build: The command '/bin/sh -c ln -s /taiga/conf.json /usr/src/taiga-front-dist/dist/conf.json' returned a non-zero code: 1
```

Can you help to fix it?

**Comment by egv** [comment]
@a93ushakov can you please post more logs?

**Comment by AvdN** [comment]
@egv what more logs do you need. This happens if you build from scratch because none of the previous steps make `/usr/src/taiga-front-dist/dist/`

**Comment by jujes** [comment]
I have the same issue...

**Comment by AvdN** [comment]
This happens if you fail to checkout the git repository recursively. (git clone --recursive ). If you don't (or use the downloaded zip file) you won't get the linked repositories from taiga that provide that directory.

**Comment by benhutchins** [comment]
Yes, you need to pull down taiga's repo that are referenced as gitmodules. Without those, it would break. Looks like @AvdN helped resolve this, so I'll close this ticket.
